#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define OCARINA_RUNTIME_POK 1

#define POK_GENERATED_CODE 1

#define POK_NEEDS_LIBC_STDLIB 1

#define POK_NEEDS_LIBC_STDIO 1

#define POK_NEEDS_CONSOLE 1

#define POK_CONFIG_NB_THREADS 2

#define POK_CONFIG_STACKS_SIZE 16384

#define POK_NEEDS_THREADS 1

#define POK_NEEDS_TIME 1

#define POK_NEEDS_PARTITIONS 1

//#define POK_NEEDS_LIBC_STRING 1
#define POK_NEEDS_PROTOCOLS 1
#define POK_NEEDS_PORTS_QUEUEING 1

#endif
