#include "activity.h"
#include "gtypes.h"
#include <types.h>
#include "deployment.h"
#include <core/thread.h>
#include <middleware/port.h>
#include <assert.h>
#include <core/time.h>
#include <core/partition.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
uint32_t pok_threads[POK_CONFIG_NB_THREADS];
uint8_t pr1_pdataout_id;

extern uint8_t pr1_pdataout_id;

/* void* thr_job (void) */
/* { */
/*     while (1)  { */
/*     } */
/* } */

int main (void)
{
    /* single thread scenario */
    while(1) {
        asm volatile (".fill 0x100000, 1, 0x90");
    }

    /* pok_thread_attr_t tattr; */
    /* pok_ret_t ret; */

    /* /\* ret = pok_port_queueing_create ( *\/ */
    /* /\*                                 "pr1_pdataout", *\/ */
    /* /\*                                 2 * sizeof (int), *\/ */
    /* /\*                                 POK_PORT_DIRECTION_OUT, *\/ */
    /* /\*                                 POK_PORT_QUEUEING_DISCIPLINE_FIFO, *\/ */
    /* /\*                                 &(pr1_pdataout_id)); *\/ */

    /* ret = pok_thread_attr_init (&(tattr)); */
    /* ASSERT_RET(ret); */
    /* tattr.stack_size = 4096; */
    /* tattr.entry = thr_job; */

    /* tattr.period = pok_time_milliseconds (100); */
    /* tattr.time_capacity = -1; //pok_time_milliseconds (100); */
    /* //tattr.deadline = pok_time_milliseconds (100); */

    /* ret = pok_thread_create (&(pok_threads[1]), &(tattr)); */
    /* ASSERT_RET(ret); */
    /* pok_partition_set_mode (POK_PARTITION_MODE_NORMAL); */
    return (0);
}


